### ISSUE TITLE
Genome' object has no attribute 'props'

### ISSUE THREAD

**Issue by qxuchn** [vanheeringen-lab/genomepy#92]
With the new version of `genomepy = 0.8.1`, when I using `props`, it will has error. Did you changed this function? It works with `genomepy = 0.7.2`.

```from genomepy import Genome
genome = "hg38"
g = Genome(genome)
gsize = g.props["sizes"]["sizes"]
```
AttributeError: 'Genome' object has no attribute 'props'

**Comment by siebrenf** [comment]
Yes! 

to get the file path use `g.sizes_file`
to get a dict with sizes, use `g.contig_sizes()`, then use `g.sizes`
to get plugin information, use `g.plugin` instead of the old `g.props` (sizes is not a plugin anymore)

**Comment by qxuchn** [comment]
I got it. Thanks!
